### ISSUE TITLE
Research Process Page model

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/joplin#43] opened 2018-01-03 18:53 UTC
Support process page template which supports residents needing to be able learn about and apply for jobs.

- [ ] Need to discuss when job/process page is inactive because jobs have a window when they are open for application

- [ ] Ability to capture email address to inform residents when job window reopens- could use department's preferred email service i.e. mailchimp/microservice

related to cityofaustin/janis/issues/58

**Comment by ifsimicoded** [comment] 2018-05-24 18:36
Closing as Duplicate of https://github.com/cityofaustin/techstack/issues/396

**Closed by ifsimicoded** 2018-05-24 18:36 UTC
Labels: effort: medium
